config/routes.rb
Rails.application.routes.draw do
  root to: "root#root", as: :root
  
  resources :users do
    resources :user_photos, only: [:create, :destroy]
  end
  
  resource :session, only: [:new, :create, :destroy]
  
  resources :meetings
  
  resources :messages
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :password_hash, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :conversation_users
  has_many :all_conversations, through: :conversation_users, source: :conversation

  has_many :created_meetings, foreign_key: :creator_id, class_name: "Meeting"

  has_many :meeting_attends
  has_many :attended_meetings, through: :meeting_attends, source: :meeting
  
  has_many :user_photos
  
  has_many(
    :created_saves,
    class_name: "UserSave",
    foreign_key: :creator_id,
    primary_key: :id
  )
  
  has_many :saved_users, through: :created_saves
  
  has_many(
    :created_ignores,
    class_name: "UserIgnore",
    foreign_key: :creator_id,
    primary_key: :id
  )
  
  has_many :ignored_users, through: :created_ignores
  
  has_many( 
    :authored_messages,
    class_name: "Message",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  has_attached_file :profile_photo, :styles =>  {
    big: "600x600#",
    small: "300x300#"
  }, :default_url => "/images/missing_:style.png"
  
  validates_attachment_content_type(
    :profile_photo, 
    :content_type => /\Aimage\/.*\Z/ 
  )

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    @user = User.find_by_email(email)

    if @user
      if @user.is_password?(password)
        return @user
      end
    end

    return nil
  end

  def password=(password)
    @password = password
    self.password_hash = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_hash).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
  def already_saved_user?(user)
    return true if self.saved_user_ids.include?(user.id)
    
    false
  end
  
  def already_ignored_user?(user)
    return true if self.ignored_user_ids.include?(user.id)
    
    false
  end
  
  def conversations
    self.all_conversations.uniq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_out, only: [:new, :create]
  before_action :require_signed_in, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    
    render :index
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(signup_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    
    unless saved_user_params.empty?
      new_user = User.find(saved_user_params[:saved_user_id])
      @user.saved_users << new_user
      redirect_to user_url(@user)
      return
    end
    
    unless ignored_user_params.empty?
      new_user = User.find(ignored_user_params[:ignored_user_id])
      @user.ignored_users << new_user
      redirect_to user_url(@user)
      return
    end
    
    unless message_params.empty?
      convo = Conversation.create()
      m = current_user.authored_messages.create(contents: message_params[:message])
      
      convo.messages << m
      convo.users << current_user
      convo.users << User.find(message_params[:recipient_id])
    end

    if @user.update(profile_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to new_user_url
    else
      flash.now[:errors] = @user.errors.full_messages
    end
  end

  def signup_params
    params.require(:user).permit(:username, :email, :password)
  end

  def profile_params
    params.require(:user).permit(:username,
                                 :email,
                                 :profile_photo,
                                 :life_goals,
                                 :job,
                                 :hobbies,
                                 :reason_to_meet,
                                 :relationship_status,
                                 :personality_type)

  end
  
  def saved_user_params
    params.require(:user).permit(:saved_user_id)
  end
  
  def ignored_user_params
    params.require(:user).permit(:ignored_user_id)
  end
  
  def message_params
    params.require(:user).permit(:recipient_id, :message)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit Info</h2>
<form action="<%= user_url(@user) %>" enctype="multipart/form-data" method="POST">
	<%= auth_token %>
	<%= action_modifier("patch") %>
	
	<input type="file" name="user[profile_photo]">
	
	<br>
	
	<label>
		Username
		<input type="text" name="user[username]" value="<%= @user.username %>">
	</label>
	
	<br>
	
	<label>
		Email
		<input type="text" name="user[email]" value="<%= @user.email %>">
	</label>
		
	<br>
	
	<label>
		Life Goals
		<input type="text" name="user[life_goals]" value="<%= @user.life_goals %>">
	</label>
	
	<br>
	
	<label>
		Job(s)
		<input type="text" name="user[job]" value="<%= @user.job %>">
	</label>
	
	<br>
	
	<label>
		Hobbies
		<input type="text" name="user[hobbies]" value="<%= @user.hobbies %>">
	</label>
		
	<br>

	<label>
		Reason to meet
		<input type="text" name="user[reason_to_meet]" value="<%= @user.reason_to_meet %>">
	</label>
	
	<br>
	
	<label>
		Relationship Status
		<select name="user[relationship_status]">
			<option value="">Choose One</option>
			<option value="1" <%= "Selected" if @user.relationship_status == 1 %>>Single</option>
			<option value="2" <%= "Selected" if @user.relationship_status == 2 %>>In a new relationship</option>
			<option value="3" <%= "Selected" if @user.relationship_status == 3 %>>In a long term relationship</option>
			<option value="4" <%= "Selected" if @user.relationship_status == 4 %>>Married/Engaged</option>
		</select>
	</label>
	
	<br>
	
	<label>
		Personality Type
		<select name="user[personality_type]">
			<option value="">Choose One</option>
			<option value="1" <%= "Selected" if @user.personality_type == 1 %>>Nerdy</option>
			<option value="2" <%= "Selected" if @user.personality_type == 2 %>>Nerd-ish</option>
			<option value="3" <%= "Selected" if @user.personality_type == 3 %>>Neutral</option>
			<option value="4" <%= "Selected" if @user.personality_type == 4 %>>Bro-ish</option>
			<option value="5" <%= "Selected" if @user.personality_type == 5 %>>Bro</option>
		</select>
	</label>
		
	<br>
	
	<button>Submit</button>
</form>

app/views/users/index.html.erb
<h2>Meet your best friend</h2>
<h3>We have <%= @users.length %> friends for you to meet</h3>
<ul>
<% @users.each do |user| %>
	<li>
		<a href="<%= user_url(user) %>"><%= user.username %></a>
		<% if signed_in? %>
			<ul>
				<li>Age: <%= user.age %></li>
				<!--Save button -->
				<li>
				<% unless current_user.already_saved_user?(user) %>
					<form action="<%= user_url(current_user) %>" method="POST">
						<%= auth_token %>
						<%= action_modifier("patch") %>
						<input type="hidden" name="user[saved_user_id]" value="<%= user.id %>">
						<button>Save</button>
					</form>
					<% else %>
					<button disabled>Saved</button>
				<% end %>
				</li>
				<!--Ignore button -->
				<li>
					<% unless current_user.already_ignored_user?(user) %>
						<form action="<%= user_url(current_user) %>" method="POST">
							<%= auth_token %>
							<%= action_modifier("patch") %>
							<input type="hidden" name="user[ignored_user_id]" value="<%= user.id %>">
							<button>Ignore</button>
						</form>
						<% else %>
						<button disabled>Ignored</button>
					<% end %>
				</li>
				
				<!--Messaging -->
				<li>
					<form action="<%= user_url(current_user) %>" method="POST">
						<%= auth_token %>
						<%= action_modifier("patch") %>
						<input type="hidden" name="user[recipient_id]" value="<%= user.id %>">
						<textarea name="user[message]"></textarea>
						<button>Send Message</button>
					</form>
				</li>
				
			</ul>
		<% end %>
	</li>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="POST">
	<%= auth_token %>
	<label>
		Username
		<input type="text" name="user[username]">
	</label>
	
	<br>
	
	<label>
		Email
		<input type="text" name="user[email]">
	</label>
	
	<br>
	
	<label>
		Password
		<input type="password" name="user[password]">
	</label>
	
	<br>
	
	<button>Submit</button>
</form>

app/views/users/show.html.erb
<ul>
	<img src="<%= @user.profile_photo.url(:small) %>">
	<li><p>Username: <%= @user.username %></p></li>
	<li><p>Email: <%= @user.email %></p></li>
</ul>

<h2>Saved Users</h2>
<ul>
<% @user.saved_users.each do |user| %>
	<li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
<% end %>
</ul>

<h2>Ignored Users</h2>
<ul>
<% @user.ignored_users.each do |user| %>
	<li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
<% end %>
</ul>

<h2>Conversations</h2>
<ul>
	<% @user.conversations.each do |conversation| %>
		<li>
			<% conversation.messages.each do |message| %>
				<ul>
					<li><%= message.author.username %>: <%= message.contents %></li>
				</ul>
			<% end %>
		</li>
	<% end %>
</ul>

<a href="<%= edit_user_url %>">Edit Profile</a>